version: '3'
services:
  exposer:
    container_name: yosefrow_prometheus-exposer
    hostname: exposer
    build:
      context: ./exposer
    image: yosefrow/prometheus-exposer:1.0
    env_file:
      - ./.env
    ports:
      - 8000:8000
    restart: unless-stopped

  prometheus:
    container_name: yosefrow_prometheus-prometheus
    hostname: exposer
    image: prom/prometheus:v2.8.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    env_file:
      - ./.env
    depends_on:
      - exposer
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    container_name: yosefrow_prometheus-grafana
    image: grafana/grafana:6.0.1
    env_file:
      - ./.env
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
    prometheus_data: {}
    grafana_data: {}
