version: '3'
services:
  exposer:
    container_name: ${GROUP}_${PROJECT}-exposer
    hostname: exposer
    build:
      context: ./exposer
    image: $EXPOSER_IMAGE
    env_file:
      - ./.env
    ports:
      - $EXPOSER_PORT_EXTERNAL:8000
    restart: unless-stopped

  prometheus:
    container_name: ${GROUP}_${PROJECT}-prometheus
    hostname: prometheus
    image: $PROMETHEUS_IMAGE
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    env_file:
      - ./.env
    depends_on:
      - exposer
    ports:
      - $PROMETHEUS_PORT_EXTERNAL:9090
    restart: unless-stopped

  grafana:
    container_name: ${GROUP}_${PROJECT}-grafana
    hostname: grafana
    image: grafana/grafana:6.0.1
    env_file:
      - ./.env
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - $GRAFANA_PORT_EXTERNAL:3000
    restart: unless-stopped

volumes:
    prometheus_data: {}
    grafana_data: {}
